name: Battle Machines
description: A project for the Devathon contest
version: 1.0.0
author: Sothatsit

main: net.sothatsit.devathon2016.BattleMachines

commands:
  bmselect:
    description: 'Make a Battle Machines selection'
  bmparts:
    description: 'Add new Battle Machines parts'
  bmachine:
    description: 'Get a new battle machine'